AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Tactics:
    Description: Notification tactics the lambda executes
    Type: String

  RecipientEmailAddresses:
    Description: Notification recipient email addresses, max count is 2
    Type: CommaDelimitedList

  LambdaBundleBucketName:
    Description: Lambda bundle bucket name
    Type: String

  LambdaBundleFilename:
    Description: Lambda bundle file name
    Type: String
    Default: lambda.zip

  LambdaMemorySize:
    Description: Lambda memory size in MB
    Type: Number
    Default: 128

  LambdaTimeout:
    Description: Lambdatimeout in seconds
    Type: Number
    Default: 3

  LambdaSchedule:
    Description: Lambda execution schedule
    Type: String
    Default: rate(2 minutes)

  LambdaLogRetentionDays:
    Description: Lambda log retention period in days
    Type: Number
    Default: 7

Resources:
  LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: AllowAssumeRoleByLambda
              Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: LambdaExecutionPolicy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Sid: AllowLogCreation
                  Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-lambda

  Topic:
    Type: AWS::SNS::Topic
    Properties: 
      ContentBasedDeduplication: false
      DisplayName: !Ref AWS::StackName
      FifoTopic: false
      KmsMasterKeyId: !Ref AWS::NoValue
      Subscription: 
        - Endpoint: !Select [ "0", !Ref RecipientEmailAdresses ]
          Protocol: email
        - Endpoint: !Select [ "1", !Ref RecipientEmailAdresses ]
          Protocol: email
      TopicName: !Sub ${AWS::StackName}-topic

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref LambdaBundleBucketName
        S3Key: !Ref LambdaBundleFilename
      Environment:
        Variables:
          TACTICS: !Ref Tactics
          TOPIC_ARN: TODO
      FunctionName: !Sub ${AWS::StackName}-lambda
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs14.x
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AWS::StackName}-lambda
      RetentionInDays: !Ref LambdaLogRetentionDays

  LambdaSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: !Ref LambdaSchedule
      State: ENABLED
      Targets:
        - Arn: !GetAtt Lambda.Arn
          Id: LambdaSchedule
