name: cd

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  STACK_NAME: cignal
  LAMBDA_BUNDLE_BUCKET_NAME: cignal-lambda-bundle-bucket
  LAMBDA_BUNDLE_FILE_NAME: lambda.zip
  LAMBDA_MEMORY_SIZE: 128
  LAMBDA_TIMEOUT: 3
  LAMBDA_SCHEDULE: "0/5 * * * *"
  LAMBDA_LOG_RETENTION_DAYS: 7
  DROPS: DOT,KSM,MOVR,STAKE

  # pipeline needs further secrets: AWS_ACCESS_KEY_ID, 
  # AWS_SECRET_ACCESS_KEY, RECIPIENT_EMAIL_ADDRESSES

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: aws-actions/configure-aws-credentials@v1.5.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: |
          aws s3 mb s3://${{ env.LAMBDA_BUNDLE_BUCKET_NAME }}
          npm ci --only=prod
          tmp_dir=$(mktemp -d)
          npx @vercel/ncc@0.31.0 build --out=$tmp_dir ./index.js
          zip -j $tmp_dir/bundle.zip $tmp_dir/index.js
          aws s3 cp $tmp_dir/bundle.zip s3://${{ env.LAMBDA_BUNDLE_BUCKET_NAME }}/${{ env.LAMBDA_BUNDLE_FILE_NAME }}

      - run: |
          aws cloudformation deploy \
            --stack-name=${{ env.STACK_NAME }} \
            --template-file=./stack.yml \
            --parameter-overrides \
              Drops=${{ env.DROPS }} \
              Recipients='${{ secrets.RECIPIENTS }}' \
              LambdaBundleBucketName=${{ env.LAMBDA_BUNDLE_BUCKET_NAME }} \
              LambdaBundleFilename=${{ env.LAMBDA_BUNDLE_FILE_NAME }} \
              LambdaMemorySize=${{ env.LAMBDA_MEMORY_SIZE }} \
              LambdaTimeout=${{ env.LAMBDA_TIMEOUT }} \
              LambdaSchedule='${{ env.LAMBDA_SCHEDULE }}' \
              LambdaLogRetentionDays=${{ env.LAMBDA_LOG_RETENTION_DAYS }} \
            --capabilities=CAPABILITY_IAM \
            --no-fail-on-empty-changeset
